# Auto-genere par retrain_from_db.py (rank=family)
path: C:/Users/lhomm/SAS LHOMME DEVELOPMENT AND INNOVATION/accueil - Drive LDI/1_clients/Pierrick/mesure poisson/test/fish-vision/data/exports/yolo_family_mixed
train: images/train
val: images/val

names:
  0: Acanthuridae
  1: Balistidae
  2: Carangidae
  3: Chaetodontidae
  4: Ephippidae
  5: Haemulidae
  6: Labridae
  7: Lutjanidae
  8: Muraenidae
  9: Pomacanthidae
  10: Pomacentridae
  11: Scaridae
  12: Scombridae
  13: Serranidae
  14: Zanclidae
  15: shark
